### ISSUE TITLE
Incorrect Squiggles on official MXChip samples

### ISSUE THREAD

**Issue by rido-min** [microsoft/vscode-arduino#889]
VSCode extension for Arduino shows Squiggles for almost every official MXChip sample.

![image](https://user-images.githubusercontent.com/14916339/64658523-a970df00-d3ec-11e9-9b08-f31d9ead83c4.png)

or the next example

![image](https://user-images.githubusercontent.com/14916339/64658823-b3dfa880-d3ed-11e9-9f76-c52dd40ba5b8.png)

Note that in both cases the code compiles. Seeing the squiggles is really annoying and hurts the developer experience.

**Comment by xinyiz1226** [comment]
Thank you for reporting this. We will take a look.

**Comment by dilin-MS** [comment]
Hi @rido-min this bug is resolved in the latest Azure IoT Devce Workbench v0.10.16. Please take a look. Thanks for your participation! :)

**Comment by rido-min** [comment]
Thank you very much !! I hope this small improvement will help developers who learn Azure IoT with MXChip based boards.

**Comment by rido-min** [comment]
I still see squiggles like this:

![image](https://user-images.githubusercontent.com/14916339/67744432-bbc7cc00-f9de-11e9-902f-644b44c64736.png)

**Comment by dilin-MS** [comment]
Hi, are you using Visual Studio 2019 on your host computer? I just tested and found the issue when my computer have VS 2019 installed and the issue not occurs when I have VS 2017 on my computer.
Could you please try add `"compilerPath": "C:/Program Files (x86)/Arduino/hardware/tools/avr/bin/avr-gcc.exe"` in c_cpp_properties.json file and see if the squiggles disappear? Let's see what's the root cause.

**Comment by rido-min** [comment]
Yes, I have VS2019 installed. Once I changed the `compilerPath` the squiggles disappeared.

**Comment by rido-min** [comment]
@dilin-MS may I assume the latest version will configure the right `compilerPath`? otherwise we should reopen this issue.

**Comment by dilin-MS** [comment]
Hi, @rido-min . Yes, we will fix this issue in next workbench release. I open an [issue](https://github.com/microsoft/vscode-iot-workbench/issues/800) to track this.

**Comment by dilin-MS** [comment]
Hi @rido-min . We have fixed the issue in the latest v0.10.17 Azure IoT Device Workbench. You can try the latest bit to confirm that. Thanks for your active participation!
