### ISSUE TITLE
[Error] Exit with code=1 when uploading

### ISSUE THREAD

**Issue by StaDo0815** [microsoft/vscode-arduino#926]
I'm having this problem with uploading to my arduino mini pro  (I'm not using PlatformIO)
![Problem](https://user-images.githubusercontent.com/41636641/68678893-1f193880-055f-11ea-9ad4-3d71dca23156.PNG)

**Comment by hellyzh** [comment]
Does that work before? Are you using VSCode 1.40.0? There is a bug that unable to select serial port in the version.

**Comment by StaDo0815** [comment]
I know the bug. For that reason I'm using 1.39.2. It never worked before.

**Comment by dooriya** [comment]
@StaDo0815 Could you provide more information for this issue? E.g. your development environment, the repro steps, and the full error message/log?

At the same time, we just released a updated version for Arduino extension, could you try installing the **latest 0.2.28** from the [marketplace](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino) to check if the issue still occur with the latest 0.2.28?

**Comment by StaDo0815** [comment]
Sorry for not answering. The issue has been fixed by updating VSCode as well as the Arduino extension.
Thank you for helping out.
![Upload Done](https://user-images.githubusercontent.com/41636641/69498628-25f26480-0eea-11ea-921b-fe312df05dda.PNG)

**Comment by X-iaowh** [comment]
I also meet the same problem, it took me so much times.Then I try to rename the name of the file with an English name instead of a Chinese name,the problem was gone.

**Comment by BradBath** [comment]
I'm still having this issue. I've got the latest version of the arduino plugin for VSCode and a downgraded version of VSCode to fix a bug in the latest version where clicking Select serial port wouldn't bring anything up (version is now 1.42.1).

**Comment by chrisdreid** [comment]
Would like to request that the arduino.json (all settings files) file allow for variable tokens. https://code.visualstudio.com/docs/editor/variables-reference
